server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'admin'
    url: jdbc:postgresql://localhost:5430/customer
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka